[package]
name = "skyward-ecs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitmask = "0.5.0"
hashbrown = "0.13.1"
persist-o-vec = "0.3.1"
